import type { ScenarioTemplate } from '../types';
import type { CanvasNode, CanvasConnection } from '@/lib/types/canvas';
import { TEMPLATE_SCHEMA_VERSION } from '../types';

const nodes: CanvasNode[] = [
    {
        id: 'ecom-client',
        type: 'client',
        name: 'Client',
        x: 100, y: 250,
        width: 160, height: 80,
        sharedConfig: {
            deployment: { region: 'us-east-1' },
            display: { mode: 'expanded' },
        },
        specificConfig: { requestsPerSecond: 200, readWriteRatio: 0.6 }, // readWriteRatio ignored when workloadProfile is active
    },
    {
        id: 'ecom-apigw',
        type: 'api_gateway',
        name: 'API Gateway',
        x: 300, y: 250,
        width: 160, height: 80,
        sharedConfig: {
            deployment: { region: 'us-east-1' },
            display: { mode: 'expanded' },
            scaling: { instances: 2, nodeCapacityRps: 3000 },
            resilience: { circuitBreaker: true, automaticRetries: true },
            trafficControl: { rateLimiting: true, rateLimit: 250, rateLimitStrategy: 'token-bucket' },
        },
        specificConfig: { authEnabled: true, cors: true, requestTransformation: false },
    },
    {
        id: 'ecom-app',
        type: 'app_server',
        name: 'App Server',
        x: 500, y: 250,
        width: 160, height: 80,
        sharedConfig: {
            deployment: { region: 'us-east-1' },
            display: { mode: 'expanded' },
            scaling: { instances: 2, nodeCapacityRps: 400 },
            resilience: { circuitBreaker: false, automaticRetries: false },
        },
        specificConfig: { instanceType: 'medium', autoScaling: true, minInstances: 1, maxInstances: 10, distributedTransaction: 'none', sagaCompensation: 'choreography' },
    },
    {
        id: 'ecom-cache',
        type: 'cache',
        name: 'Product Cache',
        x: 700, y: 90,
        width: 160, height: 80,
        sharedConfig: {
            deployment: { region: 'us-east-1' },
            display: { mode: 'expanded' },
            scaling: { instances: 1, nodeCapacityRps: 10000 },
            consistency: { replicationStrategy: 'leader-follower', replicationFactor: 1 },
        },
        specificConfig: {
            engine: 'redis',
            maxMemory: '1GB',
            clusterMode: false,
            readStrategy: 'cache-aside',
            writeStrategy: 'write-through',
            evictionPolicy: 'lru',
            defaultTtl: 300,
            maxEntries: 5000,
        },
    },
    {
        id: 'ecom-db-orders',
        type: 'database_sql',
        name: 'Orders DB',
        x: 700, y: 250,
        width: 160, height: 80,
        sharedConfig: {
            deployment: { region: 'us-east-1' },
            display: { mode: 'expanded' },
            scaling: { instances: 1, nodeCapacityRps: 500 },
            consistency: { replicationStrategy: 'leader-follower', replicationFactor: 1 },
        },
        specificConfig: {
            engine: 'postgresql',
            instanceType: 'medium',
            readReplicas: 0,
            connectionPooling: true,
            replication: {
                mode: 'single-leader',
                syncMode: 'asynchronous',
                replicationLagMs: 100,
                lagVarianceMs: 20,
                catchUpOnFailover: false,
            },
            isolation: 'serializable',
            storageEngine: { type: 'b-tree', bloomFilters: false, compactionStrategy: 'leveled' },
            sharding: { enabled: false, strategy: 'hash-based', shardKey: 'id', shardCount: 4, consistentHashing: true, hotspotFactor: 0.0 },
        },
    },
    {
        id: 'ecom-mq',
        type: 'message_queue',
        name: 'Fulfillment Queue',
        x: 700, y: 410,
        width: 160, height: 80,
        sharedConfig: {
            deployment: { region: 'us-east-1' },
            display: { mode: 'expanded' },
            scaling: { instances: 1, nodeCapacityRps: 5000 },
            consistency: { replicationStrategy: 'leader-follower', replicationFactor: 1 },
            trafficControl: { rateLimiting: false },
        },
        specificConfig: {
            type: 'standard',
            visibilityTimeout: 30,
            deadLetterQueue: true,
            maxRetries: 3,
            retentionPeriod: 168,
            deliveryGuarantee: 'exactly-once',
            consumerGroupCount: 1,
            backpressure: 'block',
        },
    },
    {
        id: 'ecom-worker',
        type: 'worker',
        name: 'Fulfillment Worker',
        x: 900, y: 410,
        width: 160, height: 80,
        sharedConfig: {
            deployment: { region: 'us-east-1' },
            display: { mode: 'expanded' },
            scaling: { instances: 2, nodeCapacityRps: 400 },
            resilience: { circuitBreaker: false, automaticRetries: false },
        },
        specificConfig: {
            instanceType: 'medium',
            processingTimeMs: 100,
            jobType: 'io-bound',
            autoScaling: false,
            minInstances: 1,
            maxInstances: 10,
            maxRetries: 3,
        },
    },
    {
        id: 'ecom-db-fulfillment',
        type: 'database_sql',
        name: 'Fulfillment DB',
        x: 1100, y: 410,
        width: 160, height: 80,
        sharedConfig: {
            deployment: { region: 'us-east-1' },
            display: { mode: 'expanded' },
            scaling: { instances: 1, nodeCapacityRps: 500 },
            consistency: { replicationStrategy: 'leader-follower', replicationFactor: 1 },
        },
        specificConfig: {
            engine: 'postgresql',
            instanceType: 'medium',
            readReplicas: 0,
            connectionPooling: true,
            replication: {
                mode: 'single-leader',
                syncMode: 'asynchronous',
                replicationLagMs: 100,
                lagVarianceMs: 20,
                catchUpOnFailover: false,
            },
            isolation: 'read-committed',
            storageEngine: { type: 'b-tree', bloomFilters: false, compactionStrategy: 'leveled' },
            sharding: { enabled: false, strategy: 'hash-based', shardKey: 'id', shardCount: 4, consistentHashing: true, hotspotFactor: 0.0 },
        },
    },
];

const connections: CanvasConnection[] = [
    { id: 'ecom-c-gw', sourceId: 'ecom-client', targetId: 'ecom-apigw', protocol: 'http', bidirectional: false },
    { id: 'ecom-gw-app', sourceId: 'ecom-apigw', targetId: 'ecom-app', protocol: 'http', bidirectional: false },
    { id: 'ecom-app-cache', sourceId: 'ecom-app', targetId: 'ecom-cache', protocol: 'http', bidirectional: false },
    { id: 'ecom-app-orders', sourceId: 'ecom-app', targetId: 'ecom-db-orders', protocol: 'http', bidirectional: false },
    { id: 'ecom-app-mq', sourceId: 'ecom-app', targetId: 'ecom-mq', protocol: 'http', bidirectional: false },
    { id: 'ecom-mq-worker', sourceId: 'ecom-mq', targetId: 'ecom-worker', protocol: 'http', bidirectional: false },
    { id: 'ecom-worker-fulfill', sourceId: 'ecom-worker', targetId: 'ecom-db-fulfillment', protocol: 'http', bidirectional: false },
];

export const ecommerceTemplate: ScenarioTemplate = {
    schemaVersion: TEMPLATE_SCHEMA_VERSION,
    id: 'ecommerce',
    name: 'E-Commerce Checkout',
    difficulty: 'intermediate',
    category: 'classic',
    description: 'ACID checkout with serializable isolation, async fulfillment via MQ workers, and API gateway rate limiting to prevent abuse.',
    designRationale:
        'Checkout needs ACID writes — SQL with serializable isolation prevents ' +
        'double-spending and inventory races. Fulfillment (email, inventory, ' +
        'shipping) is async via MQ so the checkout response is fast. Product ' +
        'catalog is read-heavy and cacheable. The API Gateway rate-limits checkout ' +
        'to prevent abuse. Try removing serializable isolation and observe ' +
        'write conflicts under load.',
    tags: ['acid', 'async', 'rate-limiting', 'caching'],
    nodes,
    connections,
    scoringRubric: [
        {
            id: 'ecom-apigw',
            description: 'API Gateway with rate limiting',
            checkType: 'config',
            weight: 'required',
            params: { nodeType: 'api_gateway', field: 'rateLimiting', value: true },
        },
        {
            id: 'ecom-serializable',
            description: 'Orders DB uses serializable isolation',
            checkType: 'config',
            weight: 'required',
            params: { nodeType: 'database_sql', field: 'isolation', value: 'serializable' },
        },
        {
            id: 'ecom-mq',
            description: 'MQ for async fulfillment',
            checkType: 'topology',
            weight: 'required',
            params: { nodeType: 'message_queue' },
        },
        {
            id: 'ecom-cache',
            description: 'Cache for product catalog',
            checkType: 'topology',
            weight: 'bonus',
            params: { nodeType: 'cache' },
        },
        {
            id: 'ecom-worker',
            description: 'Worker for async job processing',
            checkType: 'topology',
            weight: 'bonus',
            params: { sourceType: 'message_queue', targetType: 'worker' },
        },
    ],
    workloadRef: 'ecommerce-v1',
    workloadProfile: {
        readLabel: 'Product views',
        writeLabel: 'Checkouts',
        archetypes: [
            {
                id: 'browse-catalog',
                label: 'Browse catalog',
                method: 'read',
                weight: 0.40,
                cacheKeyPattern: 'product:{id}',
                sampleIds: [
                    '42', '107', '283', '419', '536',
                    '621', '758', '834', '912', '67',
                    '194', '345', '478', '503', '689',
                    '712', '856', '923', '38', '171',
                ],
                sampleData: [
                    { id: '42', preview: 'Mechanical Keyboard — $149.99 · 23 in stock' },
                    { id: '107', preview: 'USB-C Hub 7-port — $49.99 · 142 in stock' },
                    { id: '283', preview: 'Laptop Stand Aluminium — $79.99 · 8 in stock' },
                    { id: '419', preview: 'Webcam 4K — $199.99 · 31 in stock' },
                    { id: '536', preview: 'Desk Lamp LED — $34.99 · 67 in stock' },
                    { id: '621', preview: 'Monitor 27" IPS — $399.99 · 5 in stock' },
                    { id: '758', preview: 'Mouse Wireless — $59.99 · 94 in stock' },
                    { id: '834', preview: 'Headphones ANC — $249.99 · 12 in stock' },
                    { id: '912', preview: 'SSD 2TB External — $129.99 · 47 in stock' },
                    { id: '67', preview: 'Ethernet Cable 10m — $12.99 · 203 in stock' },
                ],
                dbLabel: 'SELECT * FROM products WHERE id = ?',
            },
            {
                id: 'view-cart',
                label: 'View cart',
                method: 'read',
                weight: 0.10,
                cacheKeyPattern: 'cart:user_{id}',
                sampleIds: [
                    'user_101', 'user_202', 'user_303', 'user_404', 'user_505',
                    'user_606', 'user_707', 'user_808', 'user_909', 'user_010',
                ],
            },
            {
                id: 'check-stock',
                label: 'Check stock',
                method: 'read',
                weight: 0.10,
                cacheKeyPattern: 'inventory:{id}',
                sampleIds: [
                    '42', '107', '283', '419', '536',
                    '621', '758', '834', '912', '67',
                ],
                dbLabel: 'SELECT stock FROM inventory WHERE product_id = ?',
            },
            {
                id: 'checkout',
                label: 'Checkout',
                method: 'write',
                weight: 0.25,
                sampleIds: [
                    'ord_7810', 'ord_2934', 'ord_4562', 'ord_8371', 'ord_1205',
                    'ord_5629', 'ord_3048', 'ord_9417', 'ord_6183', 'ord_0756',
                ],
                dbLabel: 'BEGIN; INSERT INTO orders; UPDATE inventory; COMMIT',
                mqLabel: 'fulfill order_{id}',
            },
            {
                id: 'update-cart',
                label: 'Update cart',
                method: 'write',
                weight: 0.15,
                cacheKeyPattern: 'cart:user_{id}',
                sampleIds: [
                    'user_101', 'user_202', 'user_303', 'user_404', 'user_505',
                    'user_606', 'user_707', 'user_808', 'user_909', 'user_010',
                ],
                dbLabel: 'UPDATE carts SET items = ? WHERE user_id = ?',
            },
        ],
    },
};
